// Overloads.generated.cs
//
// Generated File. DO NOT EDIT THIS FILE. Edit Overloads.tt to change the produced file.
//
// Licensed under the EUPL, Version 1.1 only (the “Licence”).
// You may not use, modify or distribute this work except in compliance with the Licence.
// You may obtain a copy of the Licence at:
// <http://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
// A copy is also distributed with this source code.
// Unless required by applicable law or agreed to in writing, software distributed under the
// Licence is distributed on an “AS IS” basis, without warranties or conditions of any kind.

using System;
using System.Collections.Generic;
using System.Linq;
using SpookilySharp;
using NUnit.Framework;

namespace SpookyHashTesting
{
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithSByte()
        {
            SByte val = (SByte)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(SByte));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((SByte)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new SByte[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (SByte)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<SByte>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullSByteArrayUpdate()
        {
            new SpookyHash().Update((SByte[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullSByteArrayWithLength()
        {
            new SpookyHash().Update((SByte[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestSByte()
        {
            new SpookyHash().Update(new SByte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestSByte()
        {
            new SpookyHash().Update(new SByte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthSByte()
        {
            new SpookyHash().Update(new SByte[]{default(SByte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthSByte()
        {
            new SpookyHash().Update(new SByte[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionSByte()
        {
            var arr = new SByte[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (SByte)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32SByte()
        {
            SpookyHasher.SpookyHash32(new SByte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32SByte()
        {
            SpookyHasher.SpookyHash32(new SByte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32SByte()
        {
            SpookyHasher.SpookyHash32(new SByte[]{default(SByte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32SByte()
        {
            SpookyHasher.SpookyHash32(new SByte[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64SByte()
        {
            SpookyHasher.SpookyHash64(new SByte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64SByte()
        {
            SpookyHasher.SpookyHash64(new SByte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64SByte()
        {
            SpookyHasher.SpookyHash64(new SByte[]{default(SByte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64SByte()
        {
            SpookyHasher.SpookyHash64(new SByte[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128SByte()
        {
            SpookyHasher.SpookyHash128(new SByte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128SByte()
        {
            SpookyHasher.SpookyHash128(new SByte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128SByte()
        {
            SpookyHasher.SpookyHash128(new SByte[]{default(SByte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128SByte()
        {
            SpookyHasher.SpookyHash128(new SByte[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithUInt16()
        {
            UInt16 val = (UInt16)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(UInt16));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((UInt16)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new UInt16[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (UInt16)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<UInt16>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt16ArrayUpdate()
        {
            new SpookyHash().Update((UInt16[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt16ArrayWithLength()
        {
            new SpookyHash().Update((UInt16[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestUInt16()
        {
            new SpookyHash().Update(new UInt16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestUInt16()
        {
            new SpookyHash().Update(new UInt16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthUInt16()
        {
            new SpookyHash().Update(new UInt16[]{default(UInt16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthUInt16()
        {
            new SpookyHash().Update(new UInt16[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionUInt16()
        {
            var arr = new UInt16[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (UInt16)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32UInt16()
        {
            SpookyHasher.SpookyHash32(new UInt16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32UInt16()
        {
            SpookyHasher.SpookyHash32(new UInt16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32UInt16()
        {
            SpookyHasher.SpookyHash32(new UInt16[]{default(UInt16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32UInt16()
        {
            SpookyHasher.SpookyHash32(new UInt16[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64UInt16()
        {
            SpookyHasher.SpookyHash64(new UInt16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64UInt16()
        {
            SpookyHasher.SpookyHash64(new UInt16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64UInt16()
        {
            SpookyHasher.SpookyHash64(new UInt16[]{default(UInt16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64UInt16()
        {
            SpookyHasher.SpookyHash64(new UInt16[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128UInt16()
        {
            SpookyHasher.SpookyHash128(new UInt16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128UInt16()
        {
            SpookyHasher.SpookyHash128(new UInt16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128UInt16()
        {
            SpookyHasher.SpookyHash128(new UInt16[]{default(UInt16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128UInt16()
        {
            SpookyHasher.SpookyHash128(new UInt16[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithUInt32()
        {
            UInt32 val = (UInt32)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(UInt32));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((UInt32)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new UInt32[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (UInt32)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<UInt32>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt32ArrayUpdate()
        {
            new SpookyHash().Update((UInt32[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt32ArrayWithLength()
        {
            new SpookyHash().Update((UInt32[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestUInt32()
        {
            new SpookyHash().Update(new UInt32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestUInt32()
        {
            new SpookyHash().Update(new UInt32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthUInt32()
        {
            new SpookyHash().Update(new UInt32[]{default(UInt32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthUInt32()
        {
            new SpookyHash().Update(new UInt32[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionUInt32()
        {
            var arr = new UInt32[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (UInt32)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32UInt32()
        {
            SpookyHasher.SpookyHash32(new UInt32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32UInt32()
        {
            SpookyHasher.SpookyHash32(new UInt32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32UInt32()
        {
            SpookyHasher.SpookyHash32(new UInt32[]{default(UInt32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32UInt32()
        {
            SpookyHasher.SpookyHash32(new UInt32[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64UInt32()
        {
            SpookyHasher.SpookyHash64(new UInt32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64UInt32()
        {
            SpookyHasher.SpookyHash64(new UInt32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64UInt32()
        {
            SpookyHasher.SpookyHash64(new UInt32[]{default(UInt32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64UInt32()
        {
            SpookyHasher.SpookyHash64(new UInt32[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128UInt32()
        {
            SpookyHasher.SpookyHash128(new UInt32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128UInt32()
        {
            SpookyHasher.SpookyHash128(new UInt32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128UInt32()
        {
            SpookyHasher.SpookyHash128(new UInt32[]{default(UInt32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128UInt32()
        {
            SpookyHasher.SpookyHash128(new UInt32[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithUInt64()
        {
            UInt64 val = (UInt64)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(UInt64));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((UInt64)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new UInt64[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (UInt64)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<UInt64>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt64ArrayUpdate()
        {
            new SpookyHash().Update((UInt64[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullUInt64ArrayWithLength()
        {
            new SpookyHash().Update((UInt64[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestUInt64()
        {
            new SpookyHash().Update(new UInt64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestUInt64()
        {
            new SpookyHash().Update(new UInt64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthUInt64()
        {
            new SpookyHash().Update(new UInt64[]{default(UInt64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthUInt64()
        {
            new SpookyHash().Update(new UInt64[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionUInt64()
        {
            var arr = new UInt64[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (UInt64)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32UInt64()
        {
            SpookyHasher.SpookyHash32(new UInt64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32UInt64()
        {
            SpookyHasher.SpookyHash32(new UInt64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32UInt64()
        {
            SpookyHasher.SpookyHash32(new UInt64[]{default(UInt64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32UInt64()
        {
            SpookyHasher.SpookyHash32(new UInt64[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64UInt64()
        {
            SpookyHasher.SpookyHash64(new UInt64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64UInt64()
        {
            SpookyHasher.SpookyHash64(new UInt64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64UInt64()
        {
            SpookyHasher.SpookyHash64(new UInt64[]{default(UInt64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64UInt64()
        {
            SpookyHasher.SpookyHash64(new UInt64[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128UInt64()
        {
            SpookyHasher.SpookyHash128(new UInt64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128UInt64()
        {
            SpookyHasher.SpookyHash128(new UInt64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128UInt64()
        {
            SpookyHasher.SpookyHash128(new UInt64[]{default(UInt64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128UInt64()
        {
            SpookyHasher.SpookyHash128(new UInt64[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithByte()
        {
            Byte val = (Byte)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Byte));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Byte)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Byte[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Byte)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Byte>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullByteArrayUpdate()
        {
            new SpookyHash().Update((Byte[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullByteArrayWithLength()
        {
            new SpookyHash().Update((Byte[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestByte()
        {
            new SpookyHash().Update(new Byte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestByte()
        {
            new SpookyHash().Update(new Byte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthByte()
        {
            new SpookyHash().Update(new Byte[]{default(Byte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthByte()
        {
            new SpookyHash().Update(new Byte[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionByte()
        {
            var arr = new Byte[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Byte)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Byte()
        {
            SpookyHasher.SpookyHash32(new Byte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Byte()
        {
            SpookyHasher.SpookyHash32(new Byte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Byte()
        {
            SpookyHasher.SpookyHash32(new Byte[]{default(Byte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Byte()
        {
            SpookyHasher.SpookyHash32(new Byte[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Byte()
        {
            SpookyHasher.SpookyHash64(new Byte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Byte()
        {
            SpookyHasher.SpookyHash64(new Byte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Byte()
        {
            SpookyHasher.SpookyHash64(new Byte[]{default(Byte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Byte()
        {
            SpookyHasher.SpookyHash64(new Byte[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Byte()
        {
            SpookyHasher.SpookyHash128(new Byte[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Byte()
        {
            SpookyHasher.SpookyHash128(new Byte[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Byte()
        {
            SpookyHasher.SpookyHash128(new Byte[]{default(Byte)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Byte()
        {
            SpookyHasher.SpookyHash128(new Byte[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithChar()
        {
            Char val = (Char)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Char));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Char)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Char[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Char)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Char>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullCharArrayUpdate()
        {
            new SpookyHash().Update((Char[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullCharArrayWithLength()
        {
            new SpookyHash().Update((Char[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestChar()
        {
            new SpookyHash().Update(new Char[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestChar()
        {
            new SpookyHash().Update(new Char[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthChar()
        {
            new SpookyHash().Update(new Char[]{default(Char)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthChar()
        {
            new SpookyHash().Update(new Char[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionChar()
        {
            var arr = new Char[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Char)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Char()
        {
            SpookyHasher.SpookyHash32(new Char[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Char()
        {
            SpookyHasher.SpookyHash32(new Char[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Char()
        {
            SpookyHasher.SpookyHash32(new Char[]{default(Char)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Char()
        {
            SpookyHasher.SpookyHash32(new Char[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Char()
        {
            SpookyHasher.SpookyHash64(new Char[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Char()
        {
            SpookyHasher.SpookyHash64(new Char[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Char()
        {
            SpookyHasher.SpookyHash64(new Char[]{default(Char)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Char()
        {
            SpookyHasher.SpookyHash64(new Char[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Char()
        {
            SpookyHasher.SpookyHash128(new Char[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Char()
        {
            SpookyHasher.SpookyHash128(new Char[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Char()
        {
            SpookyHasher.SpookyHash128(new Char[]{default(Char)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Char()
        {
            SpookyHasher.SpookyHash128(new Char[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithInt16()
        {
            Int16 val = (Int16)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Int16));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Int16)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Int16[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Int16)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Int16>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt16ArrayUpdate()
        {
            new SpookyHash().Update((Int16[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt16ArrayWithLength()
        {
            new SpookyHash().Update((Int16[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestInt16()
        {
            new SpookyHash().Update(new Int16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestInt16()
        {
            new SpookyHash().Update(new Int16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthInt16()
        {
            new SpookyHash().Update(new Int16[]{default(Int16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthInt16()
        {
            new SpookyHash().Update(new Int16[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionInt16()
        {
            var arr = new Int16[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Int16)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Int16()
        {
            SpookyHasher.SpookyHash32(new Int16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Int16()
        {
            SpookyHasher.SpookyHash32(new Int16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Int16()
        {
            SpookyHasher.SpookyHash32(new Int16[]{default(Int16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Int16()
        {
            SpookyHasher.SpookyHash32(new Int16[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Int16()
        {
            SpookyHasher.SpookyHash64(new Int16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Int16()
        {
            SpookyHasher.SpookyHash64(new Int16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Int16()
        {
            SpookyHasher.SpookyHash64(new Int16[]{default(Int16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Int16()
        {
            SpookyHasher.SpookyHash64(new Int16[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Int16()
        {
            SpookyHasher.SpookyHash128(new Int16[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Int16()
        {
            SpookyHasher.SpookyHash128(new Int16[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Int16()
        {
            SpookyHasher.SpookyHash128(new Int16[]{default(Int16)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Int16()
        {
            SpookyHasher.SpookyHash128(new Int16[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithInt32()
        {
            Int32 val = (Int32)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Int32));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Int32)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Int32[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Int32)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Int32>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt32ArrayUpdate()
        {
            new SpookyHash().Update((Int32[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt32ArrayWithLength()
        {
            new SpookyHash().Update((Int32[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestInt32()
        {
            new SpookyHash().Update(new Int32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestInt32()
        {
            new SpookyHash().Update(new Int32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthInt32()
        {
            new SpookyHash().Update(new Int32[]{default(Int32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthInt32()
        {
            new SpookyHash().Update(new Int32[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionInt32()
        {
            var arr = new Int32[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Int32)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Int32()
        {
            SpookyHasher.SpookyHash32(new Int32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Int32()
        {
            SpookyHasher.SpookyHash32(new Int32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Int32()
        {
            SpookyHasher.SpookyHash32(new Int32[]{default(Int32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Int32()
        {
            SpookyHasher.SpookyHash32(new Int32[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Int32()
        {
            SpookyHasher.SpookyHash64(new Int32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Int32()
        {
            SpookyHasher.SpookyHash64(new Int32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Int32()
        {
            SpookyHasher.SpookyHash64(new Int32[]{default(Int32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Int32()
        {
            SpookyHasher.SpookyHash64(new Int32[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Int32()
        {
            SpookyHasher.SpookyHash128(new Int32[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Int32()
        {
            SpookyHasher.SpookyHash128(new Int32[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Int32()
        {
            SpookyHasher.SpookyHash128(new Int32[]{default(Int32)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Int32()
        {
            SpookyHasher.SpookyHash128(new Int32[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithInt64()
        {
            Int64 val = (Int64)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Int64));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Int64)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Int64[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Int64)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Int64>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt64ArrayUpdate()
        {
            new SpookyHash().Update((Int64[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullInt64ArrayWithLength()
        {
            new SpookyHash().Update((Int64[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestInt64()
        {
            new SpookyHash().Update(new Int64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestInt64()
        {
            new SpookyHash().Update(new Int64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthInt64()
        {
            new SpookyHash().Update(new Int64[]{default(Int64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthInt64()
        {
            new SpookyHash().Update(new Int64[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionInt64()
        {
            var arr = new Int64[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Int64)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Int64()
        {
            SpookyHasher.SpookyHash32(new Int64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Int64()
        {
            SpookyHasher.SpookyHash32(new Int64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Int64()
        {
            SpookyHasher.SpookyHash32(new Int64[]{default(Int64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Int64()
        {
            SpookyHasher.SpookyHash32(new Int64[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Int64()
        {
            SpookyHasher.SpookyHash64(new Int64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Int64()
        {
            SpookyHasher.SpookyHash64(new Int64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Int64()
        {
            SpookyHasher.SpookyHash64(new Int64[]{default(Int64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Int64()
        {
            SpookyHasher.SpookyHash64(new Int64[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Int64()
        {
            SpookyHasher.SpookyHash128(new Int64[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Int64()
        {
            SpookyHasher.SpookyHash128(new Int64[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Int64()
        {
            SpookyHasher.SpookyHash128(new Int64[]{default(Int64)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Int64()
        {
            SpookyHasher.SpookyHash128(new Int64[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithSingle()
        {
            Single val = (Single)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Single));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Single)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Single[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Single)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Single>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullSingleArrayUpdate()
        {
            new SpookyHash().Update((Single[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullSingleArrayWithLength()
        {
            new SpookyHash().Update((Single[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestSingle()
        {
            new SpookyHash().Update(new Single[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestSingle()
        {
            new SpookyHash().Update(new Single[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthSingle()
        {
            new SpookyHash().Update(new Single[]{default(Single)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthSingle()
        {
            new SpookyHash().Update(new Single[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionSingle()
        {
            var arr = new Single[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Single)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Single()
        {
            SpookyHasher.SpookyHash32(new Single[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Single()
        {
            SpookyHasher.SpookyHash32(new Single[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Single()
        {
            SpookyHasher.SpookyHash32(new Single[]{default(Single)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Single()
        {
            SpookyHasher.SpookyHash32(new Single[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Single()
        {
            SpookyHasher.SpookyHash64(new Single[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Single()
        {
            SpookyHasher.SpookyHash64(new Single[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Single()
        {
            SpookyHasher.SpookyHash64(new Single[]{default(Single)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Single()
        {
            SpookyHasher.SpookyHash64(new Single[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Single()
        {
            SpookyHasher.SpookyHash128(new Single[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Single()
        {
            SpookyHasher.SpookyHash128(new Single[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Single()
        {
            SpookyHasher.SpookyHash128(new Single[]{default(Single)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Single()
        {
            SpookyHasher.SpookyHash128(new Single[0], 0, -2);
        }
            }
	[TestFixture]
	public sealed partial class HashUpdateTests
	{
        [Test]
        public unsafe void UpdateWithDouble()
        {
            Double val = (Double)42;
            var sh = new SpookyHash();
            sh.Update(val);
            var h = sh.Final();
            sh = new SpookyHash();
            sh.Update(&val, sizeof(Double));
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            for(int i = 0; i != 200; ++i)
                sh.Update((Double)i);
            h = sh.Final();
            sh = new SpookyHash();
            var arr = new Double[200];
            for(int i = 0; i != 200; ++i)
                arr[i] = (Double)i;
            sh.Update(arr);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update(arr, 0, 200);
            Assert.AreEqual(h, sh.Final());
            sh = new SpookyHash();
            sh.Update((IEnumerable<Double>)arr);
            sh = new SpookyHash();
            sh.Update(arr.Select(i => i));
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullDoubleArrayUpdate()
        {
            new SpookyHash().Update((Double[])null);
        }
        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void NullDoubleArrayWithLength()
        {
            new SpookyHash().Update((Double[])null, 0, 0);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffestDouble()
        {
            new SpookyHash().Update(new Double[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffestDouble()
        {
            new SpookyHash().Update(new Double[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLengthDouble()
        {
            new SpookyHash().Update(new Double[]{default(Double)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLengthDouble()
        {
            new SpookyHash().Update(new Double[0], 0, -2);
        }
    }
    [TestFixture]
    public sealed partial class HasherTests
    {
        [Test]
        public void ArrayExtensionDouble()
        {
            var arr = new Double[200];
            for(int i = 0; i != arr.Length; ++i)
                arr[i] = (Double)i;
            var sh = new SpookyHash();
            sh.Update(arr);
            var h = sh.Final();
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(h, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(h, SpookyHasher.SpookyHash128(arr, 0, 200));
            var hSlice = SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF);
            Assert.AreNotEqual(h, hSlice);
            Assert.AreEqual(hSlice, unchecked(SpookyHasher.SpookyHash128(arr, 50, 100, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            long lHash = SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(lHash, SpookyHasher.SpookyHash64(arr));
            int hash = SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(hash, SpookyHasher.SpookyHash32(arr));
            arr = null;
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(HashCode128.Zero, unchecked(SpookyHasher.SpookyHash128(arr, 0, 200, (long)0xDEADBEEFDEADBEEF, (long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 0, 200));
            Assert.AreEqual(HashCode128.Zero, SpookyHasher.SpookyHash128(arr, 50, 100, 0xDEADBEEFDEADBEEF, 0xDEADBEEFDEADBEEF));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, unchecked((long)0xDEADBEEFDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash64(arr));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, unchecked((int)0xDEADBEEF)));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr, 0, 200));
            Assert.AreEqual(0, SpookyHasher.SpookyHash32(arr));
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest32Double()
        {
            SpookyHasher.SpookyHash32(new Double[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest32Double()
        {
            SpookyHasher.SpookyHash32(new Double[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength32Double()
        {
            SpookyHasher.SpookyHash32(new Double[]{default(Double)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength32Double()
        {
            SpookyHasher.SpookyHash32(new Double[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest64Double()
        {
            SpookyHasher.SpookyHash64(new Double[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest64Double()
        {
            SpookyHasher.SpookyHash64(new Double[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength64Double()
        {
            SpookyHasher.SpookyHash64(new Double[]{default(Double)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength64Double()
        {
            SpookyHasher.SpookyHash64(new Double[0], 0, -2);
        }
        
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeOffest128Double()
        {
            SpookyHasher.SpookyHash128(new Double[0], -1, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void ExcessiveOffest128Double()
        {
            SpookyHasher.SpookyHash128(new Double[0], 40, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentException))]
        public void ExcessiveLength128Double()
        {
            SpookyHasher.SpookyHash128(new Double[]{default(Double)}, 0, 2);
        }
        [Test]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void NegativeLength128Double()
        {
            SpookyHasher.SpookyHash128(new Double[0], 0, -2);
        }
            }
}